#!/bin/sh
# symlink config files in a pretty way

. ./init.sh # include utils

dir     qutebrowser     ~/.config
dir     alacritty       ~/.config
dir     kitty           ~/.config
dir     fontconfig      ~/.config
dir     nvim            ~/.config
dir     zathura         ~/.config
dir     dunst           ~/.config
dir     spotifyd        ~/.config
dir     spotify-tui     ~/.config
dir     picom           ~/.config
dir     mpd:$host       ~/.config
dir     ncmpcpp         ~/.config
dir     wezterm         ~/.config

dotfiles   xorg:$host
dotfiles   alsa:$host
dotfiles   tmux
dotfiles   zsh

files   xdg             ~/.config
