#!/bin/sh

# NOTE: make sure all commands are launched as background processes denoted by trailing `&`

# Kill custom dwmbar script and then
# start it up again. More information
# can be found at https://gitlab.com/J0ND03/scripts
killall dwmbarinfo; ~/.local/bin/dwmbarinfo.sh &

# Swap caps lock and escape key.
setxkbmap -option caps:ctrl_modifier &

# swap win and alt
setxkbmap -option altwin:swap_alt_win

# Set wallpaper.
feh --bg-fill ~/.wallpaper &

# start window manager
exec dwm
