#!/bin/sh

if [ "$(xrandr | grep "DP2-1 connected")" ]; then
    xrandr --output DP2-1 --above eDP1 --mode 2560x1440
    if [ "$(xrandr | grep "DP2-2 connected")" ]; then
        xrandr --output DP2-2 --left-of DP2-1 --rotate right --mode 2560x1440
    fi
fi

if [ "$(xrandr | grep "DP2-2 connected")" ]; then
    xrandr --output DP2-2 --above eDP1 --mode 2560x1440
fi
