#!/bin/sh

xrandr | grep "DP2-1 connected" \
        && xrandr --output DP2-1 --above eDP1 --mode 2560x1440 \
        && xrandr --output DP2-2 --left-of DP2-1 --rotate right --mode 2560x1440

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources
dwmblocks &
setxkbmap -option caps:ctrl_modifier
#setxkbmap -option altwin:swap_alt_win
dunst &
qutebrowser &
xinput set-prop $(xinput | grep "TPPS/2 IBM TrackPoint" | cut -f2 | cut -d'=' -f2) "libinput Accel Speed" -0.6 &
feh --bg-fill img/wallpapers/blue-mtn.png &
wmname LG3D
exec dwm
