#!/bin/sh
# Jack Davidson
#
#     top-level xinitrc

WM="ctwm"

# host-specific X configuration
(. ~/.xinitrc.$(cat /etc/hostname)) &

[ -f ~/.Xresources ] && xrdb -merge -I$HOME ~/.Xresources
setxkbmap -option compose:rctrl
setxkbmap -option caps:ctrl_modifier

# Workaround for java Swing GUIs
wmname LG3D &

# X bitmaps
([ $WM = "dwm" ] && \
    xsetroot -bitmap /usr/include/X11/bitmaps/cross_weave -fg "#FFFFFF" -bg "#AA80A0") &

([ $WM = "dwm" ] || \
	sxhkd &)

# wm-specific applications
([ $WM = "dwm" ] && dwmblocks &) &
([ $WM = "ctwm" ] && xclock -digital -norender &) &
([ $WM = "ctwm" ] && xdg_menu --format twm --root-menu /etc/xdg/menus/arch-applications.menu > ~/.config/twm-xdg.menu)

exec $WM
