#!/bin/sh
# Jack Davidson
#
#     top-level xinitrc

WM="ctwm"

# host-specific X configuration
(. ~/.xinitrc.$(cat /etc/hostname)) &


[ -f ~/.Xresources ] && xrdb -merge -I$HOME ~/.Xresources

sxhkd &

# wm-specific applications
([ $WM = "dwm" ] && dwmblocks) &
([ $WM = "ctwm" ] && xclock -digital -norender) &

setxkbmap -option compose:rctrl
setxkbmap -option caps:ctrl_modifier

# X bitmaps
([ $WM = "dwm" ] && \
    xsetroot -bitmap /usr/include/X11/bitmaps/cross_weave -fg "#FFFFFF" -bg "#444444") &

# Workaround for java Swing GUIs
wmname LG3D &

exec $WM
