#!/bin/bash
BASEDIR=~/repos/jd

if [ -z ${1} ]; then
    repos=(dwm dwmblocks dmenu st)
else
    repos=(${1});
fi

src="https://github.com/jack-davidson/"

pkgbuild() {
    repo=${1}
    echo ":: starting build for ${repo}"
    cd ${BASEDIR}
    echo "(1/3) cloning ${src}${repo}"
    git clone ${src}${repo} &> /dev/null
    echo "(2/3) entering build directory"
    cd ${repo}
    echo "(3/3) building ${repo}"
    make &> /dev/null
    echo ":: finished build for ${repo}"
}

pkginstall() {
    repo=${1}
    cd ${BASEDIR}
    echo ":: starting install for ${repo}"
    echo "(1/1) installing ${repo}"
    sudo make -C ${BASEDIR}/${repo} install
    echo ":: finished install for ${repo}"
    cd ..
}

for repo in ${repos[@]}; do
    pkgbuild ${repo}
    echo ""
done;

for repo in ${repos[@]}; do
    pkginstall ${repo}
    echo ""
done;

echo ":: successfully built and installed ${#repos[@]} packages (${repos[@]})"
