#!/bin/sh

echo ":: starting install for vim-plug"
echo "(1/1) fetching vim-plug"
curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim &> /dev/null
echo ":: finished install for vim-plug"

echo ":: starting vim-plug plugin installation"
echo "(1/2) fetching plugins"
nvim --headless +PlugInstall +qa
echo "(2/2) installing plugins"
echo ":: finished plugin installation"
