prompt_console() {
	printf "Would you like to start the Xorg server? [Y/n]"
	read START

	[ "$START" = "Y" ] && source ~/.zshrc && startx && logout
	[ "$START" = "" ] && source ~/.zshrc && startx && logout
}

[ "$TERM" = "linux" ] && prompt_console
