# ~/.zshrc 

# Plugin Loading
source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Variables
export PATH=$PATH:~/.local/bin:~/go/bin:/home/jd/.local/share/gem/ruby/3.0.0/bin
export TERM=xterm-kitty
export EDITOR=nvim
export GOPATH=~/go
export BROWSER=/usr/bin/qutebrowser
export npm_config_prefix="$HOME/.local"
export XDG_DOWNLOAD_DIR="/home/jd/dow"
export BAT_THEME="Nord"
export MANPAGER="less --use-color --color=d+b --color=P+c --color=u+g"

# Syntax Highlighting
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor regexp)

# History
HISTFILE=~/.zsh_history
HISTSIZE=5000
SAVEHIST=5000
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_ALL_DUPS

setopt autocd
bindkey -e

# Aliases
alias gs="git status"
alias grep="grep --color"
alias ls="exa"
alias t="task"
alias py="bpython"

# Completion
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*'

# Prompt
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git svn
zstyle ':vcs_info:git*' formats "-->%B%F{blue}%b%f"
precmd() {vcs_info}
setopt prompt_subst
prompt='%K{black} %F{green}%~%f${vcs_info_msg_0_}%k%F{black}%f '

plugin_update() {
    for repo in ~/.zsh/plugins/*; do
        git -C "${repo}" pull
    done
}

# enter tmux session in directory selected by fzf
ds() {
    cd $(fd . ~ --type d | fzf +m)
    zle reset-prompt
}

# widget to launch editor
editor() $EDITOR

# add widgets
zle -N ds
zle -N editor

# bind keys to widgets
bindkey '^@' ds
bindkey '^o' editor
