# ~/.zshrc 

# Variables
export PATH=$PATH:~/.local/bin:~/go/bin:/home/jd/.local/share/gem/ruby/3.0.0/bin
export TERM=xterm-kitty
export EDITOR=nvim
export GOPATH=~/go
export BROWSER=/usr/bin/qutebrowser
export npm_config_prefix="$HOME/.local"
export XDG_DOWNLOAD_DIR="/home/jd/dow"
export BAT_THEME="Nord"
export MANPAGER="less --use-color --color=d+b --color=P+c --color=u+g"

# zsh settings
setopt autocd
bindkey -e

# Aliases
alias gs="git status"
alias grep="grep --color"
alias ls="exa"
alias dev="cd ~/repos/jd/"
alias t="task"

# functions
toggle_bat_levels(){
    if [ -e "/tmp/dwmblocks:bat:show_levels" ]; then
        rm "/tmp/dwmblocks:bat:show_levels"
    else
        touch "/tmp/dwmblocks:bat:show_levels"
    fi
}

# fzfcd - cd to selected directory
fzfcd() {
  local dir
  dir=$(find ${1:-.} -path '*/\.*' -prune \
                  -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir"
  [ -z "$TMUX" ] && tmux # open tmux
}

bindkey -s '^@' '^[Qfzfcd^M'
bindkey -s '^o' '^[Qnvim^M'

# Plugin Loading
source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Syntax Highlighting
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor regexp)

# Prompt
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git svn
zstyle ':vcs_info:git*' formats "-->%B%F{blue}%b%f"
precmd() {vcs_info}
setopt prompt_subst
prompt='%K{black} %F{green}%~%f${vcs_info_msg_0_}%k%F{black}%f '

# History
HISTFILE=~/.zsh_history
HISTSIZE=5000
SAVEHIST=5000
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_ALL_DUPS
