# .bashrc

# Initialization:

	# If not running interactively, don't do anything
	[[ $- != *i* ]] && return

# Environment Variables:

	# XDG directory configuration:
		export XDG_DOWNLOADS_DIR=~/dow

	# Common variables:
		export EDITOR=nvim
		export BROWSER=qutebrowser
		export PAGER=less
		export PATH=$PATH:~/.local/bin:~/go/bin
		export MANPATH=$MANPATH:~/.local/share/man/
		export COLORTERM="truecolor"
	
	# bat configuration:
		export BAT_THEME=gruvbox

# Aliases:

    # Program Aliases:
        alias irc='weechat'
        alias v='$EDITOR $@'
        alias :q='exit'
        alias :e='$EDITOR $@'
	alias get_idf='. $HOME/dev/esp/esp-idf/export.sh'
	alias z="cd .."
	alias irc='weechat'
	alias v='$EDITOR $@'
	alias q='exit'
	alias ls='exa'

	# Git Aliases
		alias gs='git status'
		alias ga='git add'
		alias gA='git add -A'
		alias gc='git commit -a'

	# Color Aliases:
		alias grep='grep --color=always'
		alias less='less -R'
		alias dmesg='sudo dmesg --color=always'

# Colors:
	export LESS_TERMCAP_mb=$(tput bold; tput setaf 2) # green
	export LESS_TERMCAP_md=$(tput bold; tput setaf 6) # cyan
	export LESS_TERMCAP_me=$(tput sgr0)
	export LESS_TERMCAP_so=$(tput bold; tput setaf 3; tput setab 4) # yellow on blue
	export LESS_TERMCAP_se=$(tput rmso; tput sgr0)
	export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 7) # white
	export LESS_TERMCAP_ue=$(tput rmul; tput sgr0)
	export LESS_TERMCAP_mr=$(tput rev)
	export LESS_TERMCAP_mh=$(tput dim)
	export LESS_TERMCAP_ZN=$(tput ssubm)
	export LESS_TERMCAP_ZV=$(tput rsubm)
	export LESS_TERMCAP_ZO=$(tput ssupm)
	export LESS_TERMCAP_ZW=$(tput rsupm)
	export GROFF_NO_SGR=1         # For Konsole and Gnome-terminal

	# Prompt:
		RESET='[0m'
		FG1='[4;32m'
		FG2='[1;34m'
		[ -z "$SSH_CONNECTION" ] || SSH="$HOSTNAME"
		PS1='$([ -z $SSH ] || echo "(\[\e$FG2\]$SSH\[\e$RESET\])") \[\e$FG1\]\w\[\e$RESET\] > '
	
# Keys:

